### ISSUE TITLE
Automatic detection on your site whether the files to be compressed to PHAR are in a folder and move them

### ISSUE THREAD

**Issue by kenygamer** [pmt-mcpe-fun/WebApp#5]
Hello, I'm going to start referring those who use my plugins to pmt.mcpe.fun so that they can create the PHARS and upload the plugins to their servers, but it happens that when the download button is used in GitHub, a folder called "master" is created and it contains the files of the plugin. Could you add this method somehow? Thank you.

**Comment by Ad5001** [comment]
Hello,
There is already a system like this is the Phar builder system.
Is your file converted when you upload it? If so that means the website has found that there were a folder inside and so converts it.

**Comment by kenygamer** [comment]
Ok, I think there was an issue while converting files to .zip so it's my fault
I already fixed it.
Thank anyway.
> ☆∂єvєlσρєя☆
кєνιи αи∂яєωѕ

**Comment by NFGamerMC** [comment]
We do not allow self-hosted instances publicly! Otherwise Good Luck!
