### ISSUE TITLE
ehh :( (VIRUS)

### ISSUE THREAD

**Issue by ondraczsk** [pmt-mcpe-fun/WebApp#6]
I want download windows version on pmt.mcpe.fun, so i download it
after 10 seconds: Avast ! Antivirus!
Find virus: Malware-Gen on PMTSetup.exe!

**Comment by NFGamerMC** [comment]
This is due to the fact that it uses web data or somting from node.js. We can confirm that it is virus-free. Select Allow. If for som reason it is a virus we will take full responsibility

**Comment by Ad5001** [comment]
Malware gen...?
Strange thing....
