### ISSUE TITLE
Invalid plugin.yml provided

### ISSUE THREAD

**Issue by kenygamer** [pmt-mcpe-fun/WebApp#9]
```shell
1. cd /home/
2. git clone https://github.com/kenygamer/iProtector-v4.0
3. rm -rf iProtector-v4.0/.git
4. zip -r Plugin-v1.0.zip Plugin/*
```
What is wrong ?

I'd appreciate if you can COMPILE github.com/kenygamer/iProtector-v4.0,
Im unable to, if you could upload it in some file hosting service or else another place.
> ☆∂єvєlσρєя☆
кєνιи αи∂яєωѕ

**Comment by Ad5001** [comment]
Open your zip archive and tell me what's inside.

**Comment by kenygamer** [comment]
@Ad5001 Everything of github.com/kenygamer/iProtector-v4.0:
plugin.yml
resources/config.yml
src/kenygamer/iProtector/Main.php
src/kenygamer/iProtector/Area.php
> ☆∂єvєlσρєя☆
кєνιи αи∂яєωѕ

**Comment by Ad5001** [comment]
Is this in your repertory or the zip? Because an invalid plugin.yml means somethings wrong with your plugin.yml (either not valid yaml, missing or invalid fields).

**Comment by kenygamer** [comment]
@Ad5001 Yes.
Check the repository  if anything is wrong with the *plugin.yml*.
[repository](https://GitHub.com/kenygamer/iProtector-v4.0)
> ☆∂єvєlσρєя☆
кєνιи αи∂яєωѕ

**Comment by Ad5001** [comment]
Ok I see the problem with your plugin. You have multiple authors.

**Comment by Ad5001** [comment]
Try putting both into 'author' with a comma to define two of them.

**Comment by kenygamer** [comment]
@Ad5001 Thank you, issue fixed .
